language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- tools
    #- platform-tools

    # The BuildTools version used by your project
    #- build-tools-26.0.3
    - build-tools-26.0.2
    #- build-tools-25.0.3
    #- build-tools-24.0.3

    # The SDK version used to compile your project
    - $ANDROID_TARGET

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-google_apis-25
    #- sys-img-x86_64-google_apis-25
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET
    #- sys-img-x86_64-$ANDROID_TARGET
    #- sys-img-armeabi-v7a-android-17

env:
  matrix:
    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a

before_script:
  - chmod +x gradlew
  #- android list sdk --extended --no-ui --all
  #- echo "y" | android update sdk -a --no-ui --filter sys-img-$ANDROID_ABI-$ANDROID_TARGET,sys-img-x86_64-$ANDROID_TARGET
  #- android list targets

  # create emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - echo yes | sdkmanager --licenses

  #start emulator
  - emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator #waits forever, do not use

  #wait for emulator to start
  - sleep 180
  
  #- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  
  #unlock lock screen
  - adb shell input keyevent 82 &

#script: ./gradlew connectedAndroidTest
script: 
  - ./gradlew connectedCheck
#script: ./gradlew androidTestImplementation
